In [26]:
#using decision classifier 
#!/usr/bin/python3
import sklearn
from sklearn import tree
#features about apple and orange 
#here 0 means smoth and 1 means bumpy
data=[[100,0],[120,0],[135,1],[150,1]]
output=["apple","apple","Orange","Orange"]
#decision tree algo 
algo=tree.DecisionTreeClassifier()

#trainn data
trained_algo = algo.fit(data,output)
#now testing phase
predict = trained_algo.predict([[130,1]])

#printing output
print(predict)

['Orange']


In [42]:
#using dataset from sklearn 
#!/usr/bin/python
from sklearn.datasets import load_iris
#loading all data
iris=load_iris()
#printing features nam e
print(iris.feature_names)
#printing target name 
print(iris.target_names)

#training data
print(iris.data)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3

In [46]:
#!/usr/bin/python
from sklearn.datasets import load_iris
#loading all data
iris=load_iris()  

#printing features nam e
print(iris.feature_names)
#printing target name 
print(iris.target_names)

#training data
#features data
#print(iris.data)

#only setosa_data
setosa=iris.data[0:50]
print(setosa)
#targetdata means flowers data
#print(iris.target)
s_data=iris.target[0:50]
print(s_data)




['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3

In [56]:
#!/usr/bin/python
import numpy
from sklearn.datasets import load_iris
#loading all data
iris=load_iris()  

#printing features nam e
#print(iris.feature_names)


#printing target name 
print(iris.target_names)
x=[0,50,100]
only_target_training=numpy.delete(iris.target,x)
only_data_training=numpy.delete(iris.data,x)
print(only_target_training)
print(only_data_training)
print(only_target_training.size)


#training data
#features data
#print(iris.data)

#only setosa_data
#setosa=iris.data[0:50]
#print(setosa)

#targetdata means flowers data
#print(iris.target)
#s_data=iris.target[0:50]
#print(s_data)

#testing target
test_data=iris.data[x]
test_target=iris.target[x]
print(test_target)
print(test_data)



['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[3.5 1.4 0.2 4.9 3.  1.4 0.2 4.7 3.2 1.3 0.2 4.6 3.1 1.5 0.2 5.  3.6 1.4
 0.2 5.4 3.9 1.7 0.4 4.6 3.4 1.4 0.3 5.  3.4 1.5 0.2 4.4 2.9 1.4 0.2 4.9
 3.1 1.5 0.1 5.4 3.7 1.5 0.2 4.8 3.4 1.6 0.2 4.8 3.  0.1 4.3 3.  1.1 0.1
 5.8 4.  1.2 0.2 5.7 4.4 1.5 0.4 5.4 3.9 1.3 0.4 5.1 3.5 1.4 0.3 5.7 3.8
 1.7 0.3 5.1 3.8 1.5 0.3 5.4 3.4 1.7 0.2 5.1 3.7 1.5 0.4 4.6 3.6 1.  0.2
 5.1 3.3 1.7 0.5 4.8 3.4 1.9 0.2 3.  1.6 0.2 5.  3.4 1.6 0.4 5.2 3.5 1.5
 0.2 5.2 3.4 1.4 0.2 4.7 3.2 1.6 0.2 4.8 3.1 1.6 0.2 5.4 3.4 1.5 0.4 5.2
 4.1 1.5 0.1 5.5 4.2 1.4 0.2 4.9 3.1 1.5 0.1 5.  3.2 1.2 0.2 5.5 3.5 1.3
 0.2 4.9 3.1 1.5 0.1 4.4 3.  1.3 0.2 5.1 3.4 1.5 0.2 5.  3.5 1.3 0.3 4.5
 2.3 1.3

In [60]:
#using decesion algo
#!/usr/bin/python
import numpy
from sklearn import tree
from sklearn.datasets import load_iris

#loading all data
iris=load_iris()  
#printing features name
#print(iris.feature_names)

#printing target name 
print(iris.target_names)

x=[0,50,100]
only_target_training=numpy.delete(iris.target,x)
only_data_training=numpy.delete(iris.data,x,axis=0)
#print(only_target_training)
print(only_data_training)
print(only_target_training.size)

#training data
#features data
#print(iris.data)

#only setosa_data
#setosa=iris.data[0:50]
#print(setosa)
#
#targetdata means flowers data
#print(iris.target)
#s_data=iris.target[0:50]
#print(s_data)

#testing target
test_data=iris.data[x]
test_target=iris.target[x]
print(test_data)
print(test_target)

#calling algo

clf=tree.DecisionTreeClassifier()
trained=clf.fit(only_data_training, only_target_training)
output=trained.predict(test_data)
print(output)

['setosa' 'versicolor' 'virginica']
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 

In [21]:
#using decesion algo
#!/usr/bin/python
import numpy
from sklearn import tree
from sklearn.datasets import load_iris
#loading all data
iris=load_iris()  

#now splitting into test &train datasets
from sklearn.model_selection import train_test_split

x,y,z,a=train_test_split(iris.data,iris.target,test_size=0.1)
'''here
x is train_iris{all features values containing 90% }
y is remaining test_iris{10% of features }
z is train_target{all label containing 90% of iris.target}
a is  test_target {10% of iris.target }
'''

#calling algo

clf=tree.DecisionTreeClassifier()
# trained data with decision tree

trained=clf.fit(x,z)
#pridiction
output=trained.predict(y)
print(output)
print(a)
#print(y)

from sklearn.metrics import accuracy_score
check_pct= accuracy_score(a,output)
print(check_pct)

[2 0 1 1 2 1 1 2 0 0 1 0 2 1 2]
[2 0 1 1 1 1 1 2 0 0 1 0 2 1 2]
0.9333333333333333
